-- recipes-manager schema. Source of truth: .specs/ai_gen/db_schema.md.
-- Executed idempotently at backend startup by init_schema().

-- 1. Extension
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 2. Enum
DO $$ BEGIN
  CREATE TYPE quantity_type AS ENUM ('weight', 'volume');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- 3. Tables (parents before children)

CREATE TABLE IF NOT EXISTS users (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username    TEXT        NOT NULL UNIQUE,
  full_name   TEXT,
  pwd_hash    TEXT        NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS nutrition_fact_types (
  id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  TEXT NOT NULL UNIQUE,
  unit  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                TEXT        NOT NULL,
  image_filename      TEXT,
  created_by_user_id  BIGINT      REFERENCES users(id) ON DELETE RESTRICT,
  import_source       TEXT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT products_origin_xor CHECK (
    (created_by_user_id IS NULL) <> (import_source IS NULL)
  )
);

CREATE TABLE IF NOT EXISTS product_nutrition_facts (
  product_id          BIGINT          NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  nutrition_fact_id   BIGINT          NOT NULL REFERENCES nutrition_fact_types(id) ON DELETE RESTRICT,
  quantity_type       quantity_type   NOT NULL,
  amount              DOUBLE PRECISION NOT NULL CHECK (amount >= 0),
  PRIMARY KEY (product_id, nutrition_fact_id, quantity_type)
);

CREATE TABLE IF NOT EXISTS recipes (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                TEXT        NOT NULL,
  description         TEXT,
  image_filename      TEXT,
  created_by_user_id  BIGINT      REFERENCES users(id) ON DELETE RESTRICT,
  import_source       TEXT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT recipes_origin_xor CHECK (
    (created_by_user_id IS NULL) <> (import_source IS NULL)
  )
);

CREATE TABLE IF NOT EXISTS recipe_products (
  recipe_id      BIGINT          NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  product_id     BIGINT          NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  quantity_type  quantity_type   NOT NULL,
  amount         DOUBLE PRECISION NOT NULL CHECK (amount > 0),
  PRIMARY KEY (recipe_id, product_id)
);

CREATE TABLE IF NOT EXISTS recipe_stars (
  user_id     BIGINT      NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
  recipe_id   BIGINT      NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, recipe_id)
);

CREATE TABLE IF NOT EXISTS product_stars (
  user_id     BIGINT      NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
  product_id  BIGINT      NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, product_id)
);

-- 4. Indexes

CREATE INDEX IF NOT EXISTS recipes_name_trgm_idx
  ON recipes USING GIST (name gist_trgm_ops);

CREATE INDEX IF NOT EXISTS products_name_trgm_idx
  ON products USING GIST (name gist_trgm_ops);

CREATE INDEX IF NOT EXISTS recipes_created_by_user_id_idx
  ON recipes(created_by_user_id);

CREATE INDEX IF NOT EXISTS products_created_by_user_id_idx
  ON products(created_by_user_id);

CREATE INDEX IF NOT EXISTS recipe_products_product_id_idx
  ON recipe_products(product_id);

CREATE INDEX IF NOT EXISTS recipes_created_at_id_desc_idx
  ON recipes(created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS products_created_at_id_desc_idx
  ON products(created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS recipe_stars_user_created_at_idx
  ON recipe_stars(user_id, created_at DESC, recipe_id DESC);

CREATE INDEX IF NOT EXISTS product_stars_user_created_at_idx
  ON product_stars(user_id, created_at DESC, product_id DESC);

-- 5. Seed
INSERT INTO nutrition_fact_types (name, unit) VALUES
  ('Energy',    'kcal'),
  ('Protein',   'g'),
  ('Net Carbs', 'g'),
  ('Fat',       'g'),
  ('Fibers',    'g')
ON CONFLICT (name) DO NOTHING;
